### ISSUE TITLE
build kd-tree uses too much memory

### ISSUE THREAD

**Issue by komazsofi** [eEcoLiDAR/eEcoLiDAR#99] opened 2018-03-20 14:10 UTC
I tried to process 8 million point instead of 180.000 and actually the surfsara server go out of memory within 2 minutes and then automatically killed my process (highlighted in red in the error message). It seems to be like with 16GB RAM approx. from 180.000 point can be handled to build a kd-tree. I tried with 1 million point it crashed as well.

On the UvA server 8 million point already requires 36 GB memory to build the kd-tree.

What I did on the server:

firstly we need to set anaconda into the path in the terminal: export PATH=~/anaconda3/bin:$PATH

/data/GitHub/ecolidar/myPhD_escience_analysis/bash_process$ bash workflow.sh

Error:

zsofi@packer-ubuntu-16:/data/GitHub/ecolidar/myPhD_escience_analysis/bash_process$ bash workflow.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 58.8M  100 58.8M    0     0  55.2M      0  0:00:01  0:00:01 --:--:--  258M
------ Building kd-tree is started ------
**Number of points: 1815043
laserchicken_run.sh: line 17: 25894 Killed                  python $path_of_pythonscripts/kdtree_geobia_$volume.py $path_of_laserchicken $localinput$filename.las $localinput$filename._$volume$radius.pkl $radius**
------ Feature calculation is started ------
Traceback (most recent call last):
  File "/data/GitHub/ecolidar/myPhD_escience_analysis/test_laserchicken//computefea_geobia_cylinder.py", line 30, in <module>
    f = open(args.kdtree, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/data/GitHub/ecolidar/myPhD_escience_analysis/test_data/06en2_merged_kiv3._ground_height_kiv._cylinder2.5.pkl'
--------Upload is started--------
curl: Can't open '/data/GitHub/ecolidar/myPhD_escience_analysis/test_data/06en2_merged_kiv3._ground_height_kiv._cylinder2.5.pkl'!
curl: try 'curl --help' or 'curl --manual' for more information
curl: Can't open '/data/GitHub/ecolidar/myPhD_escience_analysis/test_data/06en2_merged_kiv3._ground_height_kiv._cylinder2.5.ply'!
curl: try 'curl --help' or 'curl --manual' for more information
--------Remove unnecessary files--------
rm: cannot remove '/data/GitHub/ecolidar/myPhD_escience_analysis/test_data/*.pkl': No such file or directory
rm: cannot remove '/data/GitHub/ecolidar/myPhD_escience_analysis/test_data/*.ply': No such file or directory
--------Script is finished--------
zsofi@packer-ubuntu-16:/data/GitHub/ecolidar/myPhD_escience_analysis/bash_process$

**Comment by romulogoncalves** [comment] 2018-03-20 16:31
The problem is not building the Kd-tree. It is building the Kd-tree without issues.
The issue is the neighbors query. The way it is formulated it requests the neighbors in the radius of 2.5 for every point. 

The candidate list returned by compute_cylinder_neighborhood will be enormous:
compute_cylinder_neighborhood(env_pc, target_pc, volume_description.radius) 

You are calling the function like this:
indices_cyl=compute_neighborhoods(pc, pc, InfiniteCylinder(np.float(args.radius)))

Your target_pc has to be a small set of points, i.e., you can't ask 8 million cylinders in the current system.
In this case, the target_pc is equal to the env_vc, i.e., 8 million points.

**Side note**: The VM does not have swap space and it should have to avoid simple out of memory problems. However, it would not solve this issue.

**Comment by komazsofi** [comment] 2018-03-21 08:42
OK I will define and analyze how the target points should be set optimally for our analysis and how that effect on the results. I did point by point because that is an existed methodology which easy to add as reference.

**Comment by romulogoncalves** [comment] 2018-03-21 08:48
You can also do all the points, but in a incremental way. The solution will be to split your request in multiple requests, i.e., break the target point cloud in multiple targets. Instead of asking 8  million in one go, request 250 000 at the time. For example, request 250 000, calculate features, save the features and request another 250 000, etc.

The issue is the list of pairs returned by the function:
target_tree.query_ball_tree(env_tree, radius)

query_ball_tree will return an enormous list.

**Comment by romulogoncalves** [comment] 2018-03-21 17:04
We have implemented a function which in a loop determines the NN for all the points in a target pointcloud suing a cylinder to define the area of interest. 

LiDAR data sets tend to have an uniform data distribution and it is a 2,5D data set. Hence, if we know the cylinder's base area we can then determine more or less how many points we have on each cylinder. At the moment we hard coded the average number of points per square meter (10 per square meter for NL). In the future it can be made available in the metadata so it is configurable.

Knowing the average number of points per cylinder we can then calculate how much space a list of indices for all cylinders will take for a pointcloud with N points. Then we check the computer's memory and we use it break the request in K pieces so we make sure we use at most 50% of the available memory, we could be less conservative but for leave optimization for later. The results are yield in chunks so to obtain the indices you need to do next().

So far it seems to work, but we need to validate the output. For that we need a testing data set. It has to be a data set for which calculating the neighbors of all the points fits in memory so we can verify if the iterative version of it works.

Once it is verified we will then work in the sphere and release it.

**Comment by romulogoncalves** [comment] 2018-03-27 07:03
@komazsofi could you provide us a test data set so we can close the issue?

**Comment by romulogoncalves** [comment] 2018-03-28 14:45
From now on **compute_neighborhoods** is a generator to be memory efficient. This means the user gets an iterator instead of a result. The user needs to call **next(compute_neighborhoods)** to iterate over the results. It is important that the user does not append all results yielded by the generator into a single list otherwise we will get again an **out of memory error**.

Covered by pull request https://github.com/eEcoLiDAR/eEcoLiDAR/pull/106

**Closed** 2018-04-10 15:19 UTC
Labels: enhancement, help wanted, optimizing, question
